services:
    - type: worker
      name: juice-v12
      runtime: node
      buildCommand: npm install --legacy-peer-deps
      startCommand: node index.js
      envVars:
        - key: OWNER_NUMBER
          value: 254753204154
        - key: SESSION_ID
          sync: false
        - key: SESSION_URL
          value: https://juice-v12-session-generator.onrender.com/pair
  