services:
  - type: web
    name: juice-v12
    runtime: node
    buildCommand: npm install --legacy-peer-deps
    startCommand: node index.js
    envVars:
      - key: OWNER_NUMBER
        sync: false
      - key: SESSION_ID
        sync: false
      - key: SESSION_URL
        sync: false
