'use strict';

const {
  default: makeWASocket,
  useMultiFileAuthState,
  DisconnectReason,
  fetchLatestBaileysVersion,
  makeCacheableSignalKeyStore,
  Browsers,
} = require('gifted-baileys');
const { Boom } = require('@hapi/boom');
const QRCode = require('qrcode');
const pino = require('pino');
const path = require('path');
const fs = require('fs');

const SESSION_DIR = path.join(__dirname, '..', 'data', 'session');
const MAX_RETRIES = 15;
const RETRY_DELAY = 4000;

// Silent logger — keeps console clean
const logger = pino({ level: 'silent' });

// ─── State ────────────────────────────────────────────────────
let sock            = null;
let state           = { connection: 'close' };
let linkedPhone     = null;
let qrImageBase64   = null;   // base64 data URL shown in browser
let pairingCode     = null;
let pairingExpiry   = null;
let mode            = 'idle'; // 'idle' | 'qr' | 'pair'
let retryCount      = 0;
let retryTimer      = null;
let phoneForRetry   = null;

// ─── Public getters ───────────────────────────────────────────
function getStatus() {
  const codeValid = pairingCode && pairingExpiry && Date.now() < pairingExpiry;
  return {
    connected:        state.connection === 'open',
    connection:       state.connection || 'close',
    phone:            linkedPhone,
    mode,
    pairingCode:      codeValid ? pairingCode : null,
    pairingExpiry:    codeValid ? pairingExpiry : null,
    hasQR:            !!qrImageBase64,
    retries:          retryCount,
  };
}
function getQR() { return qrImageBase64; }

// ─── Internal helpers ─────────────────────────────────────────
function ensureSessionDir() {
  if (!fs.existsSync(SESSION_DIR)) fs.mkdirSync(SESSION_DIR, { recursive: true });
}

function wipeSession() {
  try {
    if (fs.existsSync(SESSION_DIR)) fs.rmSync(SESSION_DIR, { recursive: true, force: true });
  } catch {}
  ensureSessionDir();
}

function killSocket() {
  if (!sock) return;
  try { sock.end(undefined); } catch {}
  try { sock.ws && sock.ws.close(); } catch {}
  sock = null;
}

function stopRetry() {
  if (retryTimer) { clearTimeout(retryTimer); retryTimer = null; }
}

function fullReset() {
  stopRetry();
  killSocket();
  state         = { connection: 'close' };
  qrImageBase64 = null;
  pairingCode   = null;
  pairingExpiry = null;
  mode          = 'idle';
  retryCount    = 0;
  phoneForRetry = null;
}

// ─── Socket factory ───────────────────────────────────────────
async function buildSocket() {
  ensureSessionDir();
  const { state: authState, saveCreds } = await useMultiFileAuthState(SESSION_DIR);

  // Fetch latest WA version — fall back gracefully
  let version;
  try {
    const v = await fetchLatestBaileysVersion();
    version = v.version;
    console.log(`[WA] Using WhatsApp version: ${version.join('.')}`);
  } catch {
    version = [2, 3000, 1023247704];
    console.log(`[WA] Using fallback version: ${version.join('.')}`);
  }

  const s = makeWASocket({
    version,
    auth: {
      creds: authState.creds,
      keys: makeCacheableSignalKeyStore(authState.keys, logger),
    },
    // ── Key settings for WhatsApp to accept the connection ──
    browser:              Browsers.macOS('Desktop'),
    printQRInTerminal:    false,
    logger,
    // ── Stability settings ──────────────────────────────────
    keepAliveIntervalMs:  25_000,
    connectTimeoutMs:     60_000,
    defaultQueryTimeoutMs: 60_000,
    qrTimeout:            60_000,
    retryRequestDelayMs:  2_000,
    maxMsgRetryCount:     5,
    // ── Optional features ───────────────────────────────────
    syncFullHistory:              false,
    markOnlineOnConnect:          true,
    generateHighQualityLinkPreview: false,
    emitOwnEvents:                true,
  });

  s.ev.on('creds.update', saveCreds);

  s.ev.on('connection.update', async (update) => {
    const { connection, lastDisconnect, qr } = update;
    state = { ...state, ...update };

    // QR code generated by WhatsApp
    if (qr && mode === 'qr') {
      console.log('[WA] QR received — converting to image');
      try {
        qrImageBase64 = await QRCode.toDataURL(qr, { width: 320, margin: 2 });
        console.log('[WA] QR image ready ✓');
      } catch (err) {
        console.error('[WA] QR image error:', err.message);
      }
    }

    if (connection === 'open') {
      console.log('[WA] ✅ Connected to WhatsApp!');
      retryCount    = 0;
      stopRetry();
      qrImageBase64 = null;
      pairingCode   = null;
      pairingExpiry = null;
      // Extract phone number from JID
      const jid = s.user?.id || '';
      linkedPhone   = jid.split(':')[0].split('@')[0] || linkedPhone || null;
      console.log('[WA] Linked phone:', linkedPhone);
    }

    if (connection === 'close') {
      const boom      = lastDisconnect?.error instanceof Boom ? lastDisconnect.error : null;
      const statusCode = boom?.output?.statusCode;
      console.log('[WA] Connection closed. Status code:', statusCode);

      // Unrecoverable — wipe session and stop
      if (
        statusCode === DisconnectReason.loggedOut ||
        statusCode === DisconnectReason.badSession ||
        statusCode === DisconnectReason.connectionReplaced
      ) {
        console.log('[WA] Session invalidated — wiping and resetting');
        wipeSession();
        fullReset();
        linkedPhone = null;
        return;
      }

      // Recoverable — schedule a reconnect
      if (mode !== 'idle' && retryCount < MAX_RETRIES) {
        retryCount++;
        const delay = Math.min(RETRY_DELAY * retryCount, 30_000);
        console.log(`[WA] Reconnecting in ${delay}ms (attempt ${retryCount}/${MAX_RETRIES})`);
        stopRetry();
        retryTimer = setTimeout(async () => {
          try {
            killSocket();
            if (mode === 'qr')   await _buildQR();
            if (mode === 'pair' && phoneForRetry) await _buildPair(phoneForRetry);
          } catch (err) {
            console.error('[WA] Reconnect error:', err.message);
          }
        }, delay);
      } else if (retryCount >= MAX_RETRIES) {
        console.error('[WA] Max retries reached — giving up');
        fullReset();
      }
    }
  });

  return s;
}

// ─── QR flow ──────────────────────────────────────────────────
async function _buildQR() {
  sock = await buildSocket();
}

async function startQRLogin() {
  wipeSession();
  fullReset();
  mode = 'qr';

  return new Promise(async (resolve, reject) => {
    let settled = false;

    // Poll for QR image
    const poll = setInterval(() => {
      if (qrImageBase64 && !settled) {
        settled = true;
        clearInterval(poll);
        resolve(qrImageBase64);
      }
    }, 200);

    try {
      await _buildQR();

      // Already registered (existing session)
      if (sock?.authState?.creds?.registered) {
        settled = true;
        clearInterval(poll);
        mode = 'idle';
        resolve('already-linked');
        return;
      }

      // Timeout after 25s
      setTimeout(() => {
        clearInterval(poll);
        if (!settled) {
          settled = true;
          qrImageBase64
            ? resolve(qrImageBase64)
            : reject(new Error('QR timed out — try again'));
        }
      }, 25_000);
    } catch (err) {
      clearInterval(poll);
      if (!settled) reject(err);
    }
  });
}

// ─── Pairing code flow ────────────────────────────────────────
async function _buildPair(phone) {
  sock = await buildSocket();

  // Wait for the WS to open before requesting the code
  await new Promise((resolve, reject) => {
    // Already registered
    if (sock.authState.creds.registered) { resolve(); return; }

    const timeout = setTimeout(() => reject(new Error('WS open timeout')), 30_000);

    sock.ev.on('connection.update', ({ connection }) => {
      if (connection === 'open') { clearTimeout(timeout); resolve(); }
      if (connection === 'close') { clearTimeout(timeout); reject(new Error('Connection closed before pairing')); }
    });

    // Also resolve after a safe delay if no update yet
    setTimeout(() => { clearTimeout(timeout); resolve(); }, 5_000);
  });

  if (sock.authState.creds.registered) {
    console.log('[WA] Already registered — no pairing needed');
    return 'already-linked';
  }

  // Request pairing code — digits only, no + or spaces
  const clean = phone.replace(/[^0-9]/g, '');
  console.log(`[WA] Requesting pairing code for ${clean}`);
  const code = await sock.requestPairingCode(clean);
  pairingCode   = code;
  pairingExpiry = Date.now() + 180_000; // 3 minutes
  console.log(`[WA] Pairing code: ${code} ✓`);
  return code;
}

async function startPairLogin(phone) {
  wipeSession();
  fullReset();
  mode          = 'pair';
  linkedPhone   = phone;
  phoneForRetry = phone;

  try {
    const code = await _buildPair(phone);
    return code;
  } catch (err) {
    console.error('[WA] Pair failed:', err.message);
    fullReset();
    throw new Error(err.message || 'Failed to get pairing code — try again');
  }
}

// ─── Disconnect ───────────────────────────────────────────────
async function disconnectBot() {
  linkedPhone = null;
  wipeSession();
  fullReset();
}

module.exports = { getStatus, getQR, startQRLogin, startPairLogin, disconnectBot };
